#!/usr/bin/env bash
#
# validate-rsyslog.sh
#
# Validates rsyslog as the required centralized logging layer.
#
# Purpose:
#  - Confirm the rsyslog service is installed and running
#  - Confirm the remote log directory exists
#  - Configure rsyslog to receive remote syslog on UDP 514
#  - Optionally configure TCP 514
#  - Confirm rsyslog configuration is syntactically valid
#  - Restart rsyslog after configuration changes
#  - Confirm port 514 is listening
#  - Send a test syslog message
#  - Confirm a test log file is written to disk
#
# Design:
#  - Treat this script as the hard validation gate for the logging stack
#  - Fail fast on critical validation failures
#  - Use shared library helpers where possible
#  - Keep stack-specific validation logic in this script, not the library
#
# Preconditions:
#  - Script is run with sufficient privileges
#  - install-rsyslog.sh completed successfully
#  - Shared library files are present and sourceable
#
# Postconditions:
#  - rsyslog remote reception is configured
#  - rsyslog configuration is validated
#  - rsyslog is listening on UDP 514
#  - test log message is written under /var/log/remote/
#
# Returns:
#  - 0 if rsyslog validation succeeds
#  - 1 is not used directly by this script as a final exit state
#  - 2 if a critical validation step fails
#

set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
LIB_DIR="${PROJECT_ROOT}/lib"

COMMON_LIB="${LIB_DIR}/common.sh"
SERVICE_LIB="${LIB_DIR}/service.sh"
SYSTEM_LIB="${LIB_DIR}/system.sh"

# ------------------------------------------------------------------------------
# Library loading
# ------------------------------------------------------------------------------

[[ -f "${COMMON_LIB}"  ]] || { echo "[FAIL] Missing library: ${COMMON_LIB}"; exit 2; }
[[ -f "${SERVICE_LIB}" ]] || { echo "[FAIL] Missing library: ${SERVICE_LIB}"; exit 2; }
[[ -f "${SYSTEM_LIB}"  ]] || { echo "[FAIL] Missing library: ${SYSTEM_LIB}"; exit 2; }

# shellcheck source=/dev/null
source "${COMMON_LIB}"
# shellcheck source=/dev/null
source "${SERVICE_LIB}"
# shellcheck source=/dev/null
source "${SYSTEM_LIB}"

# ------------------------------------------------------------------------------
# Constants
# ------------------------------------------------------------------------------

readonly RSYSLOG_SERVICE="rsyslog"
readonly RSYSLOG_CONFIG_FILE="/etc/rsyslog.d/10-remote.conf"
readonly REMOTE_LOG_DIR="/var/log/remote"
readonly TEST_HOSTNAME="rsyslog-validation-host"
readonly TEST_MESSAGE_TAG="rsyslog-validation"
readonly TEST_MESSAGE="rsyslog validation test message"
readonly ENABLE_TCP_SYSLOG="${ENABLE_TCP_SYSLOG:-0}"

# ------------------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------------------

require_root() {
    if [[ "${EUID}" -ne 0 ]]; then
        fail "This script must be run as root"
        return 2
    fi

    pass "Running with root privileges"
    return 0
}

require_commands() {
    step "Phase 1 — Required command checks"

    command_exists rsyslogd || return 2
    command_exists logger || return 2

    if command_exists ss >/dev/null; then
        pass "Socket inspection command available: ss"
        return 0
    fi

    if command_exists netstat >/dev/null; then
        pass "Socket inspection command available: netstat"
        return 0
    fi

    fail "Neither ss nor netstat is available for port validation"
    return 2
}

check_rsyslog_service() {
    step "Phase 2 — Service validation"

    service_exists "${RSYSLOG_SERVICE}" || return 2
    service_running "${RSYSLOG_SERVICE}" || return 2

    pass "rsyslog service validation completed"
    return 0
}

prepare_remote_log_directory() {
    step "Phase 3 — Remote log directory validation"

    ensure_directory "${REMOTE_LOG_DIR}" || return 2
    directory_exists "${REMOTE_LOG_DIR}" || return 2

    pass "Remote log directory is ready: ${REMOTE_LOG_DIR}"
    return 0
}

write_rsyslog_remote_config() {
    step "Phase 4 — Write rsyslog remote logging configuration"

    backup_file "${RSYSLOG_CONFIG_FILE}" >/dev/null 2>&1 || true

    write_file "${RSYSLOG_CONFIG_FILE}" <<EOF
# Remote syslog input and file storage
# Generated by validate-rsyslog.sh

module(load="imudp")
input(type="imudp" port="514")

$(if [[ "${ENABLE_TCP_SYSLOG}" == "1" ]]; then
cat <<'TCPBLOCK'
module(load="imtcp")
input(type="imtcp" port="514")
TCPBLOCK
fi)

template(name="RemoteLogsPath" type="string"
         string="${REMOTE_LOG_DIR}/%HOSTNAME%/%PROGRAMNAME%.log")

*.* ?RemoteLogsPath
& stop
EOF

    file_exists "${RSYSLOG_CONFIG_FILE}" || return 2
    pass "rsyslog remote configuration written"
    return 0
}

validate_rsyslog_config() {
    step "Phase 5 — rsyslog configuration syntax check"

    if rsyslogd -N1 >/dev/null 2>&1; then
        pass "rsyslog configuration syntax is valid"
        return 0
    fi

    fail "rsyslog configuration syntax validation failed"
    return 2
}

restart_rsyslog_service() {
    step "Phase 6 — Restart rsyslog"

    if systemctl restart "${RSYSLOG_SERVICE}.service" >/dev/null 2>&1; then
        pass "rsyslog service restarted"
    else
        fail "Failed to restart rsyslog service"
        return 2
    fi

    service_running "${RSYSLOG_SERVICE}" || return 2
    return 0
}

check_syslog_port() {
    step "Phase 7 — Listener validation"

    if command_exists ss >/dev/null; then
        if ss -lun | awk '{print $5}' | grep -Eq '(^|:)514$'; then
            pass "UDP 514 is listening"
        else
            fail "UDP 514 is not listening"
            return 2
        fi

        if [[ "${ENABLE_TCP_SYSLOG}" == "1" ]]; then
            if ss -ltn | awk '{print $4}' | grep -Eq '(^|:)514$'; then
                pass "TCP 514 is listening"
            else
                fail "TCP 514 is not listening"
                return 2
            fi
        fi

        return 0
    fi

    if command_exists netstat >/dev/null; then
        if netstat -lun 2>/dev/null | awk '{print $4}' | grep -Eq '(^|:)514$'; then
            pass "UDP 514 is listening"
        else
            fail "UDP 514 is not listening"
            return 2
        fi

        if [[ "${ENABLE_TCP_SYSLOG}" == "1" ]]; then
            if netstat -ltn 2>/dev/null | awk '{print $4}' | grep -Eq '(^|:)514$'; then
                pass "TCP 514 is listening"
            else
                fail "TCP 514 is not listening"
                return 2
            fi
        fi

        return 0
    fi

    fail "Unable to validate syslog listener port"
    return 2
}

send_test_message() {
    step "Phase 8 — Test message injection"

    logger -n 127.0.0.1 -P 514 -d -t "${TEST_MESSAGE_TAG}" -- "${TEST_MESSAGE}"
    if [[ $? -ne 0 ]]; then
        fail "Failed to send test syslog message"
        return 2
    fi

    pass "Test syslog message sent"
    return 0
}

verify_test_log_written() {
    step "Phase 9 — Log write validation"

    local test_log_file="${REMOTE_LOG_DIR}/127.0.0.1/${TEST_MESSAGE_TAG}.log"

    sleep 2

    if [[ ! -f "${test_log_file}" ]]; then
        warn "Expected test log file not found at: ${test_log_file}"
        info "Searching for matching validation message under ${REMOTE_LOG_DIR}"
    fi

    if grep -R --line-number --fixed-strings "${TEST_MESSAGE}" "${REMOTE_LOG_DIR}" >/dev/null 2>&1; then
        pass "Validation test message was written to disk"
        return 0
    fi

    fail "Validation test message was not found under ${REMOTE_LOG_DIR}"
    return 2
}

print_success_summary() {
    step "Validation Summary"

    pass "rsyslog is installed and running"
    pass "Remote syslog reception is configured"
    pass "Port 514 listener validation passed"
    pass "Test message was written to disk"
    info "rsyslog layer is ready for upper logging stack components"
    info "Next stages: Loki, Grafana, and Promtail"
}

main() {
    step "Validate rsyslog"

    require_root || die "Root privileges are required"
    require_commands || die "Required command validation failed"
    check_rsyslog_service || die "rsyslog service validation failed"
    prepare_remote_log_directory || die "Remote log directory validation failed"
    write_rsyslog_remote_config || die "Failed to write rsyslog remote configuration"
    validate_rsyslog_config || die "rsyslog configuration syntax validation failed"
    restart_rsyslog_service || die "Failed to restart rsyslog"
    check_syslog_port || die "Syslog listener validation failed"
    send_test_message || die "Failed to send test syslog message"
    verify_test_log_written || die "rsyslog log write validation failed"

    print_success_summary
    pass "validate-rsyslog.sh completed successfully"
    return 0
}

main "$@"
